title: Coworking Spaces
description: Explore coworking spaces across cities
baseurl: "/coworking"
url: "https://singhnatwar25.github.io"

collections:
  spaces:
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /blog/:year/:month/:day/:title/
